### ISSUE TITLE
Does not render any content

### ISSUE THREAD

**Issue by probonopd** [readium/SDKLauncher-OSX#43] opened 2015-03-14 18:32 UTC
I downloaded http://jenkinsmaster.datalogics-cloud.com:8080/view/Readium-Launcher/job/Readium-SDK-Launcher-Mac-OSX-develop/label=Mac/lastSuccessfulBuild/artifact/build/Release/Build/Products/Debug/*zip*/Debug.zip, http://jenkinsmaster.datalogics-cloud.com:8080/view/Readium-Launcher/job/Readium-SDK-Launcher-Mac-OSX-develop/label=Mac/lastSuccessfulBuild/artifact/build/Release/Build/Products/Debug/ and tried to open some ePub files, but it seems like nothing is rendered. I used test ePub files from epub-testsuite-20150314 such as epub30-test-0101-20150314.epub

Right-clicking and selecting "Reload", I get "ERROR READING HTML BYTES!".

This is on OS X 10.9.5.

I do see the TOC, metadata etc.

**Comment by datalogics-bhaugen** [comment] 2015-03-14 18:57
Interesting, when I build this myself on my mac I can open books and content renders. When I try the version that Jenkins built and you linked to @probonopd I get the following error in the console

> 3/14/15 1:56:41.802 PM LauncherOSX[23715]: Error: [<LOXPreferences 0x6000000d2980> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key enableGPUHardwareAccelerationCSS3D.

I am not sure if this is preventing the app from rendering content or not but it is the only error that I see in the console.

**Comment by probonopd** [comment] 2015-03-14 19:05
I get 
```
2015-03-14 20:02:14.268 LauncherOSX[1110:507] Error: [<LOXPreferences 0x7f92dac56990> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key enableGPUHardwareAccelerationCSS3D.
``` 
as soon as I launch the app. Then, when I open a file, I get 
```
2015-03-14 20:02:25.636 LauncherOSX[1110:507] A fallback chain MUST contain a valid EPUB Content Document.
2015-03-14 20:02:25.637 LauncherOSX[1110:507] #title is not a valid IRI: Unspecified EPUB specification error
```

**Comment by datalogics-bhaugen** [comment] 2015-03-14 19:07
@probonopd okay so at least you are getting the same error that I am getting.

@danielweck have you ever seen this before?

**Comment by datalogics-bhaugen** [comment] 2015-03-14 19:33
@probonopd I think this error I posted earlier is not the cause of the issue but this is again because the release/0.17 branch has not been merged to develop. When I built locally I forgot to reset the submodules to the correct point.

**Comment by danielweck** [comment] 2015-03-15 09:08
@probonopd thank you for your feedback. The console messages you reported do not indicate a failure per-say, as far as I can tell. Like @datalogics-bhaugen I think that the submodules references are out of date. I will fix the develop branch(es) ASAP:

https://github.com/readium/SDKLauncher-OSX/tree/develop

 f8618c4 --> 896ec4b
https://github.com/readium/readium-sdk/commits/develop

8303a0b--> f2a32b1
https://github.com/readium/readium-shared-js/commits/develop

**Comment by danielweck** [comment] 2015-03-15 09:16
Fixed: https://github.com/readium/SDKLauncher-OSX/commit/89d8bb67e664ad7609d833f24731d5d1b47e311f

**Closed by danielweck** 2015-03-15 09:16 UTC
